#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include <vector>

#include <QString>

namespace definitions {

extern const std::vector<QString> path_code_blocks;
extern const QString path_keywords;
extern const QString path_functions;
extern const QString path_actions_key;

enum IconPos {
	ICON_APERTURE = 0,
	ICON_ARROW_DOWN,
	ICON_ARROW_LEFT,
	ICON_ARROW_RIGHT,
	ICON_ARROW_UP,
	ICON_AUDIO,
	ICON_BOOKMARK,
	ICON_BURN,
	ICON_CALCULATOR,
	ICON_CAMERA,
	ICON_CARET_DOWN,
	ICON_CARET_LEFT,
	ICON_CARET_RIGHT,
	ICON_CARET_UP,
	ICON_CARET_UP_DOWN,
	ICON_CHECKBOX,
	ICON_CHEVRON_DOWN,
	ICON_CHEVRON_LEFT,
	ICON_CHEVRON_RIGHT,
	ICON_CHEVRON_UP,
	ICON_CLOCK,
	ICON_CODE,
	ICON_COMMENT,
	ICON_COMPASS,
	ICON_CONTRAST,
	ICON_DOCUMENT,
	ICON_DOLLAR,
	ICON_DOWNLOAD,
	ICON_EJECT,
	ICON_ENVELOPE,
	ICON_EXCERPT,
	ICON_EYE,
	ICON_FILE,
	ICON_FLAG,
	ICON_FLASH,
	ICON_GEAR,
	ICON_HOME,
	ICON_IMAGE,
	ICON_INFINITY,
	ICON_INFO,
	ICON_KEY,
	ICON_LIGHTNING,
	ICON_LIST,
	ICON_LOCK_LOCK,
	ICON_LOCK_UNLOCK,
	ICON_LOGIN,
	ICON_LOGOUT,
	ICON_LOOP,
	ICON_MARKER,
	ICON_MICROPHONE,
	ICON_MOON,
	ICON_MOVE,
	ICON_MUSIC,
	ICON_PENCIL,
	ICON_PLUS,
	ICON_PULSE,
	ICON_RANDOMIZE,
	ICON_RECORD,
	ICON_RELOAD,
	ICON_RESIZE_HEIGHT,
	ICON_RESIZE_WIDTH,
	ICON_SCRIPT,
	ICON_SEARCH,
	ICON_SHIELD,
	ICON_TAG,
	ICON_TARGET,
	ICON_THUMBS_DOWN,
	ICON_THUMBS_UP,
	ICON_TIMER,
	ICON_TRANSFER,
	ICON_TRASH,
	ICON_UNDO,
	ICON_WRENCH,
	ICON_NUM
};

extern const std::vector<QString> icon;
}

#endif // DEFINITIONS_H
